version: 2.1
parameters:
  run-build-and-deploy-main:
    type: boolean
    default: true
  run-build-and-deploy-pr:
    type: boolean
    default: true
  run-deploy-test-to-live:
    type: boolean
    default: false
  run-build-and-deploy-mu:
    type: boolean
    default: false
  data-source-url:
    type: string
    default: "dev-presales-wp-decoupled-demo.pantheonsite.io"
  destination-env:
    type: string
    default: ""

workflows:
  version: 2
  build_and_deploy_main:
    when:
      and:
        - << pipeline.parameters.run-build-and-deploy-main >>
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - pfe/gatsby-build-and-deploy:
          pre-steps:
            - pfe/gh-status:
                state: "pending"
                target_url: $CIRCLE_BUILD_URL
                description: "Starting Gatsby Build"
                context: "pantheon/webops"
          post-steps:
            - pfe/gh-status:
                state: "success"
                target_url: "https://$TERMINUS_ENV--$TERMINUS_SITE.my.pantheonfrontend.website/"
                description: "Deployment complete"
                context: "pantheon/webops"
          data-source-url: << pipeline.parameters.data-source-url >>
          destination-env: << pipeline.parameters.destination-env >>
  build_and_deploy_pr:
    # https://circleci.com/docs/2.0/configuration-reference/#using-when-in-workflows
    when:
      and:
        - << pipeline.parameters.run-build-and-deploy-pr >>
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - pfe/gatsby-build-and-deploy:
          pre-steps:
            - pfe/gh-status:
                state: "pending"
                target_url: $CIRCLE_BUILD_URL
                description: "Starting Gatsby build"
                context: "pantheon/webops"
          post-steps:
            - pfe/gh-status:
                state: "success"
                target_url: "https://$TERMINUS_ENV--$TERMINUS_SITE.my.pantheonfrontend.website/"
                description: "Deployment complete"
                context: "pantheon/webops"
          data-source-url: << pipeline.parameters.data-source-url >>

  build_and_deploy_mu:
    when: << pipeline.parameters.run-build-and-deploy-mu >>
    jobs:
      - pfe/gatsby-build-and-deploy:
          data-source-url: << pipeline.parameters.data-source-url >>
          managed-update: true
          destination-env: << pipeline.parameters.destination-env >>

  deploy_test_to_live:
    when: << pipeline.parameters.run-deploy-test-to-live >>
    jobs:
      - pfe/deploy-test-to-live

orbs:
  pfe: pantheon-systems/front-end@0.3.0
